# Site
repository: pavelpavlenko/pavelpavlenko.github.io
favicon: images/favicon.ico


# Content configuration version
version: 2

# Personal info
name: Pavlenko Pavel
title: Software Developer
email: bprog.kg@gmail.com
website: pavelpavlenko.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username:
github_username:  pavelpavlenko
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: pavel-pavlenko-ph-d-b1b046216
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/robot2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pavel and I'm a software engineer. I have worked at a number of companies gaining teamwork and leadership skills.
  What I enjoy most is automating various devices and processes and creating tools to manage them.

  I am most skilled in: <mark>Golang</mark> and <mark>Javascript</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Driver alert system
        sub_title: Warning system for drivers about the presence of pedestrians using hogdescriptor
        caption: November 2014 - October 2015
        quote: >
          The system helps reduce the number of accidents at an unregulated intersection.

        description: | # this will include new lines to allow paragraphs
          I designed and developed a system that detects the presence of people at a pedestrian intersection and sends a signal to change the color of the light signal on the road sign (yellow and red).
          The system is completely autonomous and was installed at 2 intersections in the city of Bishkek.

          Skills: <mark>C++</mark> <mark>OpenCV</mark> <mark>Ubuntu</mark> <mark>Cmake</mark> <mark>Algorithms</mark> <mark>Arduino</mark> <mark>CubiBoard A20</mark> <mark>Gmock</mark> <mark>Hogdescriptor</mark> <mark>Multithreading</mark> <mark>Networking</mark>
                  
          ![](/images/projects/ped_hog.png){:width="80%"}{:style="display:block; margin-left:auto; margin-right:auto;"}
          ![](/images/projects/sign.jpg){:width="80%"}{:style="display:block; margin-left:auto; margin-right:auto;"}
          ![](/images/projects/sign_blink.gif){:width="80%"}{:style="display:block; margin-left:auto; margin-right:auto;"}

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pepex company
        link: pepex.kg
        # link_text: pepex.kg
        sub_title: Software engineer
        caption: November 2018 - Present
        quote: >
          
        description: | # this will include new lines to allow paragraphs
           

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Academy of Science of Kyrgyz Republic, Institute of Automation and Information Technology
        caption: 2013 - 2016
        sub_title: Ph.D. System Analysis, Control & Information Processing
        description: | # this will include new lines to allow paragraphs
          Thesis Title: Development of an adaptive control system based on fuzzy logic and traffic modeling in a metropolis with information processing

      - layout: left
        title: Kyrgyz Technical University
        caption: 1997 - 2003
        sub_title: Engineer Automation and Management in Technical Systems
        description: | # this will include new lines to allow paragraphs
          Topic of the thesis: Automated personnel management system

  - title: Volunteering # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seminars and trainings
        link:
        # link_text: boringcompany.com
        sub_title: Seminars and trainings for students
        caption: October 2018 - Present
        quote: >

        description: | # this will include new lines to allow paragraphs
          Sometimes I conduct seminars and trainings for students of Kyrgyz State Technical University named after I.Razzakov (KGUSTA) 
          
          ![](/images/seminars/first.jpeg){: width="50%"}{: style="display:block; margin-left: auto; margin-right: auto;"}
          ![](/images/seminars/second.jpeg){: width="50%"}{: style="display:block; margin-left: auto; margin-right: auto;"}

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Robots
      - Reading
      - Hiking in the mountains

      Look at this cool image. I use these things to implement interesting and useful ideas. :))  
      ![Board collection](images/board_collection.png "Collection")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
